### ISSUE TITLE
adding packages to your frameworks

### ISSUE THREAD

**Issue by glentner** [beeware/Python-Apple-support#1]
It's not clear to me how to add python packages (with compiled components) to your projects (i.e., `pip install $something`). If I want to use Pandas in an iOS app, how can I go about this?

**Comment by freakboy3742** [comment]
The short answer is that it isn't easy - you need to be able to compile the binary component for multiple architectures (x86_64, i386, armv7, armv7s, arm64), and combine them as a Framework that can be included in your iOS app.

I've added build processes for OpenSSL, BZip2 and XZ to this support package, as they're the Python builtin modules that are commonly needed. Popular packages like Pandas would also be a good candidate to add to this list, at least as an optional include. 

Alternatively, [briefcase](http://pybee.org/project/projects/tools/briefcase/) could be extended to help automate the process of building the binary components of a package.

So - I'm open to suggestions.

**Comment by AlexanderCollins** [comment]
How would you go about compiling the binary components for said architectures and then make a framework/ what process did you use?

**Comment by freakboy3742** [comment]
@AlexanderCollins Essentially the process is to integrate the code for the binary module into the overall Python project. If you do this at the source code level, the cross-compilation process is handled for you; but you have to work out how to put the code into your XCode project. If you package your binary module as a static library, you have to manage the compilation process yourself (which isn't easy); but you can just drop the library into a project and it should Just Work.

If you go down the compilation path, you need to compile the library for each platform, and then use a tool called `lipo` to combine the binary for each platform into what is called a `fat` binary - a binary that contains code for multiple architectures.

The best guide to this compilation process that I can suggest is the Python-Apple-Support tools themselves. If you trace through the compilation process for XZ or BZ2, you'll see how the tool is compiled multiple times, and combined into a single static binary in a framework.

**Comment by cculianu** [comment]
So it's not possible to use libraries such as eg Cryptodome which have embedded .so files, correct?

**Comment by freakboy3742** [comment]
@cculianu It *can* be done, but it's a complex process. See my comments on issue #56 that you raised.

**Comment by cculianu** [comment]
Awesome -- saw that.  Thanks!

👍

**Comment by freakboy3742** [comment]
Closing as the original question has been answered.
