### ISSUE TITLE
Trouble Building NumPy

### ISSUE THREAD

**Issue by siege098** [beeware/Python-Apple-support#112]
**Describe the bug**
when I build NumPy with `make numpy-macOS` it fails with the following error.

`Running setup.py install for numpy ... error
ERROR: Command errored out with exit status 1: /Users/cambisjfarahmandi/Developer/Python-Apple-support-3.9/build/macOS/python/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ky/q6by_ndx5znd2kn40jv7hq940000gn/T/pip-req-build-r7rfd00_/setup.py'"'"'; __file__='"'"'/private/var/folders/ky/q6by_ndx5znd2kn40jv7hq940000gn/T/pip-req-build-r7rfd00_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/ky/q6by_ndx5znd2kn40jv7hq940000gn/T/pip-record-s7w7v66b/install-record.txt --single-version-externally-managed --home /private/var/folders/ky/q6by_ndx5znd2kn40jv7hq940000gn/T/pip-target-l0t05ck6 --compile --install-headers /private/var/folders/ky/q6by_ndx5znd2kn40jv7hq940000gn/T/pip-target-l0t05ck6/include/python/numpy Check the logs for full command output.`

I also get the following error

'fatal error: 'endian.h' file not found'

Any ideas on how to resolve this?

**Comment by wangjunhui2015** [comment]
make: /Users/dahuilang/Downloads/Python-Apple-support-3.9/build/macOS/python/bin/python3: No such file or directory
make: *** [pip] Error 1
