### ISSUE TITLE
Include module when packaging beeware using briefcase for MacOS

### ISSUE THREAD

**Issue by hoffenmerCode** [beeware/Python-Apple-support#121]
Newbie using briefcase and loving it. 
I have a simply code that includes a twilio module in my python code (import twilio) in my main app. 
When I dev or run the app on my mac = works.
When I package it using briefcase with --no-sign, the dmg app never opens on my mac. 
When I remove the (import twilio) from the code and update and repackage, then it works again. 

Why? What am I missing? Please help. I don't want to go back to pyQt :)

**Comment by freakboy3742** [comment]
The most likely culprit I can think of would be missing dependencies.

When you added the twilio libraries, you've clearly done a `pip install twilio` - but did you also add `twilio` to the `requires` list in `briefcase.toml`? Briefcase builds a completely isolated environment for packaged apps, so you need to explicitly declare any dependencies so it knows what to put into that environment.

Once you've done that and re-packaged the app, the dependency will be included (you should see it being installed as part of the packaging process) - with any luck, the app will then start the same as it does in dev mode.

**Comment by hoffenmerCode** [comment]
> The most likely culprit I can think of would be missing dependencies.
> 
> When you added the twilio libraries, you've clearly done a `pip install twilio` - but did you also add `twilio` to the `requires` list in `briefcase.toml`? Briefcase builds a completely isolated environment for packaged apps, so you need to explicitly declare any dependencies so it knows what to put into that environment.
> 
> Once you've done that and re-packaged the app, the dependency will be included (you should see it being installed as part of the packaging process) - with any luck, the app will then start the same as it does in dev mode.

Perfect. Worked. Thank you!
