### ISSUE TITLE
Cant Build

### ISSUE THREAD

**Issue by nsmith1024** [beeware/Python-Apple-support#124]
Hello,

Im trying to use/install this for IOS from scratch, so i followed the steps, but when i type make IOS it doesnt do anything, see below....

user@Ns-Mac-mini py % 
user@Ns-Mac-mini py % git clone https://github.com/beeware/Python-Apple-support.git
Cloning into 'Python-Apple-support'...
remote: Enumerating objects: 1549, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 1549 (delta 11), reused 15 (delta 4), pack-reused 1519
Receiving objects: 100% (1549/1549), 4.34 MiB | 5.47 MiB/s, done.
Resolving deltas: 100% (789/789), done.
user@Ns-Mac-mini py % cd Python-Apple-support 
user@Ns-Mac-mini Python-Apple-support % ls -la
total 32
drwxr-xr-x   7 user  staff   224 Jul 23 08:52 .
drwxr-xr-x   6 user  staff   192 Jul 23 08:52 ..
drwxr-xr-x  12 user  staff   384 Jul 23 08:52 .git
-rw-r--r--   1 user  staff    62 Jul 23 08:52 .gitignore
-rw-r--r--   1 user  staff   177 Jul 23 08:52 CONTRIBUTING.md
-rw-r--r--   1 user  staff  1069 Jul 23 08:52 LICENSE
-rw-r--r--   1 user  staff  1891 Jul 23 08:52 README.rst
user@Ns-Mac-mini Python-Apple-support % make iOS
make: *** No rule to make target `iOS'.  Stop.
user@Ns-Mac-mini Python-Apple-support % 

Is there more instructions on how to do it?

Thanks

**Comment by dgelessus** [comment]
This is mentioned in [the README](https://github.com/beeware/Python-Apple-support#readme):

> The master branch of this repository has no content; there is an independent branch for each supported version of Python. The following Python versions are supported: [...]

You need to check out one of the branches listed there before you can run the build.

**Comment by nsmith1024** [comment]
Thanks for the info, but i dont see the branches, i tried clicking on different links but i keep ending up back here.

Im trying to do the IOS one can you post a link for that branch?

Thanks

**Comment by freakboy3742** [comment]
So... the branches are all listed in this pull down: 

<img width="386" alt="Screen Shot 2021-07-25 at 11 09 22 am" src="https://user-images.githubusercontent.com/37345/126886420-8aaee5e9-d3a9-410e-ab1e-53a1fdfab4cb.png">

The links to branches are all linked in the README:

<img width="465" alt="Screen Shot 2021-07-25 at 11 09 29 am" src="https://user-images.githubusercontent.com/37345/126886433-a54dc8ef-99c7-4659-b49d-4984f46ba460.png">

For example, [this is the URL of the 3.9 branch](https://github.com/beeware/Python-Apple-support/tree/3.9). 

`git clone <repo URL>` by itself will always give you the master branch; you then need to check out the branch of the repository that you need. `git checkout 3.9` for example, will check out the 3.9 branch.
