### ISSUE TITLE
Error building numpy-iOS

### ISSUE THREAD

**Issue by carybakker** [beeware/Python-Apple-support#128]
**Describe the bug**
make numpy-iOS fails on 3.9 branch for me

**To Reproduce**
1. checkout 3.9 branch
2. make iOS
3. make numpy-iOS
4. build fails

**Expected behavior**
Successful build of numpy-iOS

**Environment:**
 - Operating System: MacOS 11.4
 - Python version: I have 3.9.1 but in this case, it's irrelevant since it's all downloaded and built 
 - Software versions: Python-Apple-support 3.9

**Build error**

<working path>/Python-Apple-support/build/macOS/python/bin/python3 -m ensurepip
make: <working path>/Python-Apple-support/build/macOS/python/bin/python3: No such file or directory
make: *** [pip] Error 1

python3 does exist, but it's not at the ./build/macOS/python/bin/python3 location...
the path is ./build/macOS/Python-3.9.6/dist/bin/python3

I created a soft link to Python-3.9.6 with:

`ln -s ./Python-3.9.6/dist ./python`

This allows the build to continue, but the build errors out with:

distutils.errors.CompileError: Command "xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mios-version-min=8.0 -fembed-bitcode -c /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.c -o /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.o -MMD -MF /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.o.d" failed with exit status 1
make: *** [build/iOS/packages/numpy/build/temp.iphonesimulator.x86_64-3.9/libpymath.a] Error 1

And an error further up reported is:

C compiler: xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mios-version-min=8.0 -fembed-bitcode

creating /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/var
creating /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/var/folders
creating /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/var/folders/z3
creating /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn
creating /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T
creating /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c
compile options: '-c'
xcrun: /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.c
clang: warning: using sysroot for 'MacOSX' but targeting 'iPhone' [-Wincompatible-sysroot]
clang: warning: using sysroot for 'MacOSX' but targeting 'iPhone' [-Wincompatible-sysroot]
/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.c:4:13: error: implicit declaration of function 'zungqr_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            zungqr_();
            ^
/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.c:4:13: note: did you mean 'zungqr'?
/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.c:1:6: note: 'zungqr' declared here
void zungqr();
     ^
1 error generated.
clang: warning: using sysroot for 'MacOSX' but targeting 'iPhone' [-Wincompatible-sysroot]
clang: warning: using sysroot for 'MacOSX' but targeting 'iPhone' [-Wincompatible-sysroot]
/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.c:4:13: error: implicit declaration of function 'zungqr_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            zungqr_();
            ^
/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.c:4:13: note: did you mean 'zungqr'?
/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.c:1:6: note: 'zungqr' declared here
void zungqr();
     ^
1 error generated.
Traceback (most recent call last):
  File "/Users/carybakker/dev/junk/embed_python/Python-Apple-support/build/iOS/packages/numpy/numpy/distutils/unixccompiler.py", line 57, in UnixCCompiler__compile
    self.spawn(self.compiler_so + cc_args + [src, '-o', obj] + deps +
  File "/Users/carybakker/dev/junk/embed_python/Python-Apple-support/build/iOS/packages/numpy/numpy/distutils/ccompiler.py", line 89, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "/Users/carybakker/dev/junk/embed_python/Python-Apple-support/build/iOS/packages/numpy/numpy/distutils/ccompiler.py", line 152, in CCompiler_spawn
    raise DistutilsExecError('Command "%s" failed with exit status %d%s' % (cmd, s, msg))
distutils.errors.DistutilsExecError: Command "xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mios-version-min=8.0 -fembed-bitcode -c /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.c -o /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.o -MMD -MF /var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/var/folders/z3/5156tl1n16785d9p8yhkrm540000gn/T/tmp8tietm9c/source.o.d" failed with exit status 1

**Comment by freakboy3742** [comment]
Closing as we're deprecating the numpy build system provided by this project, in favour of a more comprehensive approach to support binary packages.
