### ISSUE TITLE
 No module named 'numpy' On Python 3.10

### ISSUE THREAD

**Issue by LengQH** [beeware/Python-Apple-support#134]
<img width="937" alt="图片" src="https://user-images.githubusercontent.com/13087205/159403282-0c42a68f-cc11-47a2-9227-c8117d7ea087.png">

**Comment by freakboy3742** [comment]
It is not at all clear what is being reported here. You've provided a screenshot of part of a stack trace, without any context for what you were trying to do, or how the error was generated. Closing on that basis.

If you want to provide more details on what you were trying to do, and how someone else might reproduce the same error, we can re-open this ticket.
