### ISSUE TITLE
Modulemap for macOS Python.xcframework

### ISSUE THREAD

**Issue by rehatkathuria** [beeware/Python-Apple-support#151]
In order to properly utilise the macOS `Python.xcframework` I am adding a `module.modulemap` with the following contents:

```
module Python {
  umbrella header "Python.h"
  export *
  link "Python"
}

```

inside `Python.xcframework/macos-arm64_x86_64/Headers`

However, the above warns me about certain parts of the framework not being exported. I would really appreciate it if I could get some guidance on an appropriate modulemap to ensure I'm able to use the framework on macOS.

The above, when I attempt to use the framework, as expected, results in build errors pointing to undefined symbols.

I have attached a sample project for reference:

https://github.com/rehatkathuria/BeewarePythonMacOSSampelproject

**Comment by freakboy3742** [comment]
The currently supported mechanism for using this support package is to use Briefcase. While we're definitely interested in making the modifications required to turn this into a "fully compliant" macOS module, that's not a configuration we currently support. 

We're open to any patches to correct this situation, though.

**Comment by rehatkathuria** [comment]
It looks like the modulemap wasn't the issue here. I have managed to whittle away at the symbols not being found by adding

→ `libncurses.5.4.tbd`
→ `SystemConfiguration.framework`

There are still some symbols failing to be found which I think belong to `libFFI`. 

https://github.com/rehatkathuria/BeewarePythonMacOSSampelproject/commit/01d47ca339cde851ae82a5989c00eac3982f66ec

**Comment by freakboy3742** [comment]
Yes - there are a number of dependent libraries that need to be included in a project; if you generate an empty project with Briefcase, you'll be able to see a working configuration.

**Comment by rehatkathuria** [comment]
Final missing link was `libpanel.tbd`. Closing. Thanks!
