### ISSUE TITLE
How to use python to call c++functions in the project of iOS physical devices

### ISSUE THREAD

**Issue by chenzb2015** [beeware/Python-Apple-support#173]
### What is the problem or limitation you are having?

How to use python to call c++functions in the project of iOS physical devices

### Describe the solution you'd like

So far, I haven't found a method to use python to call c++in iOS projects

### Describe alternatives you've considered

So far, I haven't found a method to use python to call c++in iOS projects

**Comment by freakboy3742** [comment]
Binding to C++ libraries isn't an issue that is specific to this project, or even to iOS; it's a general problem of language interoperability. Tools like [PyBind11](https://pybind11.readthedocs.io/en/stable/) may be helpful.
