### ISSUE TITLE
Using the manual installation (without briefcase), is there any way to install third party library like numpy ? 

### ISSUE THREAD

**Issue by johnfhima** [beeware/Python-Apple-support#175]
### Describe the bug

I have successfully completed your tutorial for the manual installation. I would like to use add python code to a swift project that already exist. Nevertheless I need numpy inside this code. Could you explain me what I should do to be able to install third part library (like numpy) ? 

Thanks

### Steps to reproduce

--

### Expected behavior

--

### Environment

--

**Comment by freakboy3742** [comment]
Yes, you can install third party libraries; however, the process isn't simple. There's a reason Briefcase exists :-)

If it's a pure Python package, you can install the package into your source tree somewhere (`pip install --target <some folder> <pkgname>` will be useful here), ensure those resources are included in your app bundle, then configure your Python installation to include that path as part of your `PYTHONPATH`/`sys.path`.

If it's a binary package (like numpy), it's more complicated. You need to either obtain or build a compiled binary wheel that contains 2 .so files - one for the simulator ABI (potentially with 2 architectures - arm64 and x86_64), and one for the device ABI. You can get *some* precompiled binary wheels from [the BeeWare iOS wheel repository](https://anaconda.org/beeware/repo) - if you use `pip install --prefer-binary --extra-index-url https://pypi.anaconda.org/beeware/simple --target <some folder> <pkgname>`, you can install those wheels into your target packages folder. If the binary you want isn't in that repository, you need to build your own - at present, that isn't a simple proposition, but [this folder](https://github.com/freakboy3742/chaquopy/tree/iOS-support/server/pypi) contains the tools that were used to build the BeeWare packages.

Any .so files that are part of wheels then need to be signed with the app's signature. 

It's very difficult to provide step-by-step instructions, as the specifics are entirely dependent on your own app. The best advice I can give you is to generate a test project using `briefcase`, passing in the `-v` option - that will show you all the commands that Briefcase is running under the hood; the generated Xcode project includes the build steps to sign the binary wheel libraries.

**Comment by johnfhima** [comment]
Thanks for your fast answer. Indeed it looks complicated and I am not sur I get everything. Is there any place I could find some details for the different step ? 
Let's assume I create a briefcase project. How can I use what have been generated inside an existing project to embed python with the libraries installed with briefcase ?

Thanks

**Comment by freakboy3742** [comment]
We haven't really documented the steps - mostly because our focus is on using Briefcase to make the process as simple as possible for end users. 

As for how to use what Briefcase generates - Briefcase generates an Xcode project; so compare, contrast and combine with your own project; and the process by which Briefcase generates what it does can be revealed by running any Briefcase command with `-v` to show the command line that was executed.

**Comment by johnfhima** [comment]
Thanks. But I am a bit lost using briefcase. The Xcode project it build me is not a classical one (swift UI or storyboard). I want my swift code to be able to run python function but I don't want to write an app without swift.
Could you then explain me how could I create a project using briefcase and then use it as a regular swift project( ie storyboard) ?

**Comment by freakboy3742** [comment]
This support package is enough to give you access to the Python embedded C API; the Briefcase projects shows you the Objective-C and Xcode settings that are needed to access that API. Those fundamentals won't change with a swift project; although the code invoking the C API will obviously change.

I believe [PythonKit](https://github.com/pvieito/PythonKit) might be more helpful for Swift projects; but I haven't used it myself.

**Comment by johnfhima** [comment]
I didn't understood your previous answer...
When laughing an Xcode project written by briefcase it opens a project fully in python. Which files should I keep / remove / add in order to be able to use the python code (even with PythonKit) ? 

Thanks a lot for your help !

**Comment by johnfhima** [comment]
Thanks a lot for your previous answer. After investigating a bit more the content you provided me, I succeed to import successfully pillow (which I think is pure python). But didnt succeed to make numpy work even from the command you provided me (pip install --prefer-binary --extra-index-url https://pypi.anaconda.org/beeware/simple --target <some folder> <pkgname>).
Maybe I didn't understood well what you meant by "you can install those wheels into your target packages folder".
In any case I assume this is the last missing part because numpy is inside the list of the precompiled binary wheels.

Thanks again! 

Here is the error that I have





PythonKit/Python.swift:706: Fatal error: 'try!' expression unexpectedly raised an error: Python exception: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/Users/jonathanfhima/Library/Developer/CoreSimulator/Devices/D61A6656-A683-4EEF-9AAD-AB77AA21B75D/data/Containers/Bundle/Application/727267BE-A0FC-4F46-ABEA-DBF52ECBA370/test.app/test"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

Traceback:
  File "/Users/jonathanfhima/Library/Developer/CoreSimulator/Devices/D61A6656-A683-4EEF-9AAD-AB77AA21B75D/data/Containers/Bundle/Application/727267BE-A0FC-4F46-ABEA-DBF52ECBA370/test.app/lib/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/Users/jonathanfhima/Library/Developer/CoreSimulator/Devices/D61A6656-A683-4EEF-9AAD-AB77AA21B75D/data/Containers/Bundle/Application/727267BE-A0FC-4F46-ABEA-DBF52ECBA370/test.app/lib/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)

2023-02-07 19:54:48.544716+0200 test[6696:897679] PythonKit/Python.swift:706: Fatal error: 'try!' expression unexpectedly raised an error: Python exception: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/Users/jonathanfhima/Library/Developer/CoreSimulator/Devices/D61A6656-A683-4EEF-9AAD-AB77AA21B75D/data/Containers/Bundle/Application/727267BE-A0FC-4F46-ABEA-DBF52ECBA370/test.app/test"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

Traceback:
  File "/Users/jonathanfhima/Library/Developer/CoreSimulator/Devices/D61A6656-A683-4EEF-9AAD-AB77AA21B75D/data/Containers/Bundle/Application/727267BE-A0FC-4F46-ABEA-DBF52ECBA370/test.app/lib/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/Users/jonathanfhima/Library/Developer/CoreSimulator/Devices/D61A6656-A683-4EEF-9AAD-AB77AA21B75D/data/Containers/Bundle/Application/727267BE-A0FC-4F46-ABEA-DBF52ECBA370/test.app/lib/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)

**Comment by johnfhima** [comment]
Finally by changing the version of the python installed to 3.9 I succeed to import numpy. Nevertheless I can't import scikit-image. Here is the error I have. 
Thanks for your help
<img width="1129" alt="Capture d’écran 2023-02-07 à 22 50 15" src="https://user-images.githubusercontent.com/61589415/217362427-312f2943-cd86-4275-989a-c881a303a11f.png">

**Comment by johnfhima** [comment]
It also not work to install scikit-image using briefcase. Is there any other option to install this library ?

**Comment by freakboy3742** [comment]
`scikit-image` hasn't been pre-compiled for iOS because of some complications - it's dependent on numpy, and while we're able to build numpy, using numpy as a build dependency is complicated because of how numpy is packaged. 

The option for installing the library is "work out how to compile it for iOS". As I indicated previously, [this folder](https://github.com/freakboy3742/chaquopy/tree/iOS-support/server/pypi) includes the build setup for iOS packages, and there's a configuration there for `scikit-image`; however, that build configuration doesn't work on iOS at present. Fix that, and you'll have iOS wheels.

**Comment by johnfhima** [comment]
I got it. I am currently trying to have a look at the chaquopy/server/pypi repo.
Do you have any more insight about why the scikit-image build configuration provided by the repos does not work for iOS in order to have the direction on where to look ?

Jonathan Fhima

**Comment by freakboy3742** [comment]
The problem is the process of building the wheel itself. Python/pip doesn't have a strong concept of "Cross platform" builds;  it's assumed that the Python you're using to run "pip" is the platform where you're using the code. That's a problem for iOS, because you're not running pip *on* iOS; and when it comes to building a package, you're building on macOS, but want a wheel for iOS.

In the case of scikit-image, it requires numpy to be in the build environment; and while we can build numpy itself, we haven't yet been able to "trick" the build process that the version we want installed is the iOS version, rather than the macOS version  that it will find by default.

It might be possible to make use of tools like [crossenv](https://github.com/benfogle/crossenv) to work around this; As I understand it, that's a more comprehensive approach to cross-platform environments, but I haven't actually tried with iOS (or Android, for that matter) to see if it will address the issues we're seeing.

There's also the issue of PEP517-compliant builds; at present, the build tools in that repository are pinned at a version of pip that didn't require or use PEP517 build isolation. That's something that is preventing us from publishing a more recent version of numpy, because newer versions of numpy use Meson to build binary components (rather than setuptools).

**Comment by mhsmith** [comment]
For scikit-image, the larger obstacle is that it requires SciPy, which requires a Fortran compiler, and last time we checked there was [no fully working Fortran compiler for iOS](https://meow464.neocities.org/blog/state-of-fortran-on-ios/).

**Comment by freakboy3742** [comment]
Where is the SciPy dependency specified? The meta.yaml [only declares a dependency on Cython and Numpy](https://github.com/chaquo/chaquopy/blob/master/server/pypi/packages/scikit-image/meta.yaml)

**Comment by mhsmith** [comment]
Unlike a real conda recipe, our meta.yaml files only include the requirements to build a package, not to run it. [Here](https://github.com/scikit-image/scikit-image/blob/v0.18.3/requirements/default.txt) are scikit-image's runtime requirements.

**Comment by johnfhima** [comment]
PS: I tried to signed my binaries with the following script:

set -e
echo "Signing as $EXPANDED_CODE_SIGN_IDENTITY_NAME ($EXPANDED_CODE_SIGN_IDENTITY)"
find "$CODESIGNING_FOLDER_PATH/python-stdlib/lib-dynload" -name "*.so" -exec /usr/bin/codesign — force — sign "$EXPANDED_CODE_SIGN_IDENTITY" -o runtime — timestamp=none — preserve-metadata=identifier,entitlements,flags — generate-entitlement-der {} \;


find "$CODESIGNING_FOLDER_PATH/lib/numpy/" -name "*/*.so" -exec /usr/bin/codesign — force — sign "$EXPANDED_CODE_SIGN_IDENTITY" -o runtime — timestamp=none — preserve-metadata=identifier,entitlements,flags — generate-entitlement-der {} \;

**Comment by johnfhima** [comment]
In case we assume that I am not interested in the entire scikit image library but in one specific function (the _fast_skeletonize one from this address https://github.com/scikit-image/scikit-image/blob/00177e14097237ef20ed3141ed454bc81b308f82/skimage/morphology/_skeletonize_cy.pyx) which rely only on numpy and cnumpy. Is there a way to include it in my project?

Otherwise thanks a lot for you help I succeed to run a pure python version of this function (but the time required by each run is definitely way more longer than the original version)

**Comment by johnfhima** [comment]
Also when I tried to upload the Hellowold briefcase on TestFlight I have the following error.
Do you know how I could solved it ? 


<img width="1006" alt="Capture d’écran 2023-02-08 à 20 30 06" src="https://user-images.githubusercontent.com/61589415/217620114-9d19621a-b477-466c-a88f-1a1efae5d185.png">

**Comment by freakboy3742** [comment]
Ah - that's... annoying. It appears the structure generated by Briefcase is being rejected by the App Store. 

My immediate guess is that the code that is currently being included in the `python-stdlib` and `app_packages` folders will need to be moved to the Frameworks folder; possibly inside a directory structure that gives the appearance of an iOS Framework.

**Comment by mhsmith** [comment]
> In case we assume that I am not interested in the entire scikit image library but in one specific function (the _fast_skeletonize one from this address https://github.com/scikit-image/scikit-image/blob/00177e14097237ef20ed3141ed454bc81b308f82/skimage/morphology/_skeletonize_cy.pyx) which rely only on numpy and cnumpy. Is there a way to include it in my project?

You could build your own package which contains only that one Cython module. Use the [build tool](https://github.com/freakboy3742/chaquopy/tree/iOS-support/server/pypi) that @freakboy3742 linked above, and base your recipe on [this example](https://github.com/chaquo/chaquopy/tree/master/server/pypi/packages/cython-example).

I agree that it looks like the module only depends on NumPy, but it also has a `cimport` statement, which means it'll require NumPy at build time. We already have one iOS package with a build-time NumPy requirement (pandas), so it's possible this will work, but I'm not certain.

**Comment by UnrealCherry** [comment]
I met it too. How do I fix it

**Comment by mhsmith** [comment]
@UnrealCherry: If you mean your app has been rejected by the App Store, see #176. Otherwise, please create a new issue.
