### ISSUE TITLE
iOS apps rejected by App Store

### ISSUE THREAD

**Issue by freakboy3742** [beeware/Python-Apple-support#176]
### Describe the bug

Via @johnfhima at https://github.com/beeware/Python-Apple-support/issues/175#issuecomment-1423064843

Apps packaged using this support package are being rejected by the App Store due to app structure.

### Steps to reproduce

1. Generate a HelloWorld app for iOS
2. Push that app to TestFlight
3. See error "Invalid Bundle Structure - The binary file '...' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles."

<img width="1006" alt="Capture d’écran 2023-02-08 à 20 30 06" src="https://user-images.githubusercontent.com/61589415/217620114-9d19621a-b477-466c-a88f-1a1efae5d185.png">

### Expected behavior

App should not be rejected by App Store.

### Environment

- Operating System: iOS, possibly macOS
- Python version: all

### Additional context

The error message referred to by the App Store links to [this document](https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle?language=objc). It suggests the 

[@mhsmith edit: This error is also discussed at [Technical Note TN2435](https://developer.apple.com/library/archive/technotes/tn2435/_index.html)]

A similar problem likely exists for macOS apps pushed to the App Store.

It's possible the app_packages and python-stdlib folders need to be moved to a "fake" Python framework package in a `/Frameworks` location.

**Comment by samschott** [comment]
Oh, that is annoying! I'm not particularly familiar with either iOS packaging requirements or Python builds, but would a "real" framework build work here? Similar to what the macOS Python installer installs in `Library/Frameworks/Python.framework` on macOS?

**Comment by freakboy3742** [comment]
That's definitely going to be my first pass at a solution. The problem that I foresee is that I'm don't know how aggressive App Store validation is on having "a single library with the same name as the framework" as a requirement. We need to have dozens of .so files, named as .so files, in specific directory structures. I certainly hope we don't need to process every Python module into it's own `.framework` so that iOS is happy...

**Comment by rickymohk** [comment]
I am also facing this issue. I tried putting all python stuffs into a framework, and use this framework in an app, but it still produces the error when validating. How does kivy pull this off?

**Comment by freakboy3742** [comment]
I have checked Kivy for a while, but last time I played with it, they solve the problem by avoiding it completely, and static compiling the binary modules. This approach is guaranteed to work, as all the library code in the main executable, but it prevents distributing packages as binary wheels.

**Comment by rickymohk** [comment]
I understand Kivy is merging the binaries in to the main executable, but I get confused when inspecting the app package content produced by Kivy. There are still .so files inside (e.g. in <AppName>.app/lib/python3.0/site-packages/) . So I wonder 1. why it still contains .so files when they already merge the binaries into the main exe and 2. why app store validation doesn't care about these .so files.

**Comment by freakboy3742** [comment]
Like I said, I haven't looked at Kivy for a while, so I don't know for sure. However, (a) are you sure they're included in the final published app bundle, not just the intermediate compilation artefacts; and (b) that Kivy apps *are* accepted by the iOS App Store? (b) in particular doesn't seem especially likely, but it would be an explanation.

**Comment by rickymohk** [comment]
After further inspection, turns out that the .so files packaged in the Kivy app are empty files, probably just placeholders. They use a custom importer to redirect the .so import for precompiled modules. Now I am able to use a Kivy generated XCode project as a barebone (without compiling the kivy recipe, only compile python and numpy), rename its main function and expose by a bridging header, then add my Swift files with new entry point and start develop with Swift and PythonKit from there.

**Comment by johnfhima** [comment]
Hi @rickymohk, could you provide some documentation/additional explanation about how can I implement your solution? 

This would be really helpful.

**Comment by rickymohk** [comment]
> Hi @rickymohk, could you provide some documentation/additional explanation about how can I implement your solution?
> 
> This would be really helpful.

Forgive me if it is not suitable to talk too deep into Kivy in this BeeWare thread. Here is how I did it:

1. Follow https://kivy.org/doc/stable/guide/packaging-ios-prerequisites.html#packaging-ios-prerequisites
2. Run `pip install kivy-ios`
3. Create a project folder and cd into it
4. Run `toolchain build numpy`
5. Create a dummy app folder(e.g. dummyapp) with a file named "main.py"
6. Run `toolchain create AppName ./dummyapp` An XCode project folder named "appname-ios" will be created
7. Open the created XCode project (e.g. appname-ios/appname.xcodeproj)
8. Select signing team
9. Edit "main.m"
    1. Extract the necessary initialization code (set `PYTHONHOME`, `PYTHONPATH`, `load_custom_builtin_importer()`, `Py_Initialize()`, etc.) from `int main(int argc, char *argv[])` into a `void initPython()`
        1. Don't call `Py_Finalize()` since it breaks numpy (It throws `Python exception: No module named '_posixsubprocess'` when using numpy if `Py_Finalize()` is called. I figured this out by trial, don't know exactly what it does or its impact. Will be happy if someone could explain it)
    2. Remove `int main(int argc, char *argv[])` and `void export_orientation();`
    3. Remove unused headers, leave only "Foundation.h" and "Python.h"
10. Create "main.h", write `void initPython();` into it
11. Add Swift files (e.g. AppName.swift) as new entry point (with `@main` in it, such as your SwfitUI App, or AppDelegate if you use Storyboard), with create bridging header file
12. Write `#import "main.h"` in the bridging header (e.g. appname-Bridging-Header.h)
13. You now have a Swift project with Python environment and numpy support. Call `initPython()` in your entry point then use PythonKit to invoke Python codes.

**Comment by johnfhima** [comment]
@rickymohk Thanks a lot for your help. I am trying to follow your instruction but I don't really know what is the necessary part of the main function that should be moved to the initPython function.

In case you feel it is not appropriate to give more information about ivy on this thread maybe you could send it to me by email (in my GitHub bio).


Thanks a lot again, it is few weeks I try to find a solution

**Comment by rickymohk** [comment]
> @rickymohk Thanks a lot for your help. I am trying to follow your instruction but I don't really know what is the necessary part of the main function that should be moved to the initPython function.
> 
> In case you feel it is not appropriate to give more information about ivy on this thread maybe you could send it to me by email (in my GitHub bio).
> 
> Thanks a lot again, it is few weeks I try to find a solution

This is how my `void iniyPython()` ending up

``` Objective-C
void initPython()
{
    NSAutoreleasePool * pool = [[NSAutoreleasePool alloc] init];

    // Change the executing path to YourApp
    chdir("YourApp");

    // Special environment to prefer .pyo, and don't write bytecode if .py are found
    // because the process will not have a write attribute on the device.
    putenv("PYTHONOPTIMIZE=2");
    putenv("PYTHONDONTWRITEBYTECODE=1");
    putenv("PYTHONNOUSERSITE=1");
    putenv("PYTHONPATH=.");
    putenv("PYTHONUNBUFFERED=1");
    putenv("LC_CTYPE=UTF-8");
    // putenv("PYTHONVERBOSE=1");
    // putenv("PYOBJUS_DEBUG=1");
    
    // IOS_IS_WINDOWED=True disables fullscreen and then statusbar is shown
    putenv("IOS_IS_WINDOWED=False");
    
    
    NSString * resourcePath = [[NSBundle mainBundle] resourcePath];
    NSString *python_home = [NSString stringWithFormat:@"PYTHONHOME=%@", resourcePath, nil];
    putenv((char *)[python_home UTF8String]);

    NSString *python_path = [NSString stringWithFormat:@"PYTHONPATH=%@:%@/lib/python3.9/:%@/lib/python3.9/site-packages:.", resourcePath, resourcePath, resourcePath, nil];
    putenv((char *)[python_path UTF8String]);

    NSString *tmp_path = [NSString stringWithFormat:@"TMP=%@/tmp", resourcePath, nil];
    putenv((char *)[tmp_path UTF8String]);

    NSLog(@"Initializing python");
    Py_Initialize();
    
    // If other modules are using the thread, we need to initialize them before.
//    PyEval_InitThreads();
    
    // Add an importer for builtin modules
    load_custom_builtin_importer();
    
//    Py_Finalize();
    NSLog(@"Leaving");

    [pool release];
}
```

**Comment by johnfhima** [comment]
@rickymohk 
Thanks again. I am really sorry to still need your help. 
I have followed your explanation until the step 12 and created an AppDelegate file with bridging header.
But I don't know how to set it as starting point of my project (I have also created a storyboard and fill the is Initial View Controller).

I am really sorry. But normally it is the last point I am missing. 
(I have already used pythonKit so this should be more okay to me)

**Comment by johnfhima** [comment]
@rickymohk 
Did you succeed to install cocoa pods dependencies? 
Trying to install TensorFlow lite but it leads to several errors (while in a non ivy project it is working fine).

**Comment by ydesgagn** [comment]
@freakboy3742 let's try to talk 15 minutes this week. This is easy to fix.

1. We need to fix this repo so the libs are built with `-shared` instead of `-bundle` for all Apple SDKs. We need to update the patch files for all branches and I'm not too sure how to do it. When I tested it, there is always something failing, so clearly I was not doing the proper thing. Currently when you run `file math.cpython-310-iphoneos.so` you have `Mach-O 64-bit bundle arm64`. After the change, it should be `Mach-O 64-bit dynamically linked shared library arm64`
2. Apple doesn't allow mixing lib types in the same framework (.a and .so/.dylib) so we need to create a second framework with the content of `lib-dynload` or many frameworks. The load time of an iOS app is proportional to the number of dynamically linked shared libraries loaded so might be best to let the users add only the frameworks that they really need.

I have a bash script I can give you to create the frameworks above.

Ping me and we can align to close this.

Briefcase will also have to be changed when downloading pre-built wheels to extract the .so and create the frameworks on the fly (same bash script can be used as above).

**Comment by freakboy3742** [comment]
@ydesgagn I'm in Utah for PyCon US at the moment; so catching up should be a lot easier than it would normally be. I'll drop you a message on Discord to coordinate

**Comment by lin-it** [comment]
There is another problem I found that .so cannot be used in the online package of appstore

**Comment by freakboy3742** [comment]
FYI - The PRs that have been linked to this ticket are sufficient to resolve the problem; Travel Tips has been updated and published using pre-release versions of these PRs: https://apps.apple.com/au/app/travel-tips/id1336372310?platform=iphone

**Comment by Porizm** [comment]
Did you try to compress lib-dynload in zip file and extract on launch to app's document?

**Comment by KodaKoder** [comment]
Will the dylib update / App Store support be merged on the main or we have to use the dylib branch?
Thanks

**Comment by freakboy3742** [comment]
@KodaKoder It will be merged - we just need to get everything polished first. There's a lot of moving pieces that we need to be finalised:

* Support package build changes to produce wheels in the new dylib format
* Briefcase template changes to accomodate the new dylib format
* Changes to Briefcase to modify the process of deploying wheels
* Updates to the wheel building tools to generate new-style dylibs.
* Actually build and publish new-style dylib wheels.

We're also using point (4) as an opportunity to rework how we build dylib wheels, integrating `crossenv` rather than the ad hoc approach we've used to date. 

This is my personal top priority at the moment; I'm hoping to have things finalised by the end of the month.

**Comment by ydesgagn** [comment]
@freakboy3742 let me know if I can help with something.

**Comment by KodaKoder** [comment]
I will test the branch today with a little an app I will report if I encounter any problems

**Comment by freakboy3742** [comment]
@KodaKoder You may want to wait until I've flagged the PRs as ready for review before starting on that testing. I'm still making changes that will impact on your ability to test this code.
