### ISSUE TITLE
Hi, I have a question about numpy

### ISSUE THREAD

**Issue by GongWeiBinGitHub** [beeware/Python-Apple-support#177]
### Describe the bug

Excuse me，When I introduced numpy, a problem was "Original error was: No module named 'numpy.core._multiarray_umath"

### Steps to reproduce

PyImport_ImportModule()  later, PyErr_Print();

### Expected behavior

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/private/var/containers/Bundle/Application/541381C0-D316-4379-813D-F6DD78434A02/CiBoShiApp.app/CiBoShiApp"
  * The NumPy version is: "1.20.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

### Environment

iOS 16.2
Mac m2

### Logs

```

```

**Comment by freakboy3742** [comment]
It sounds like you've adding numpy as Python sources, but haven't included any of the binary components that are necessary for numpy to work.

You haven't provided enough details to reproduce your problem; but your reference to `PyImport_ImportModule` suggests you might have built your own Xcode project and have dropped this support package into your project. Adding binary modules such as `numpy` requires additional handling. If you want to see an example of this, [Briefcase](https://github.com/beeware/briefcase) is able to deploy numpy as a binary module; if you build a simple Briefcase iOS project that uses numpy, you may be able to compare with your own project to work out where you've gone wrong.

**Comment by GongWeiBinGitHub** [comment]
Glad to see your reply，I read the briefcase and I found it was a tutorial packaged as an application, maybe my understanding is wrong, I hope you can provide a document

**Comment by GongWeiBinGitHub** [comment]
How to package for an ios project

**Comment by GongWeiBinGitHub** [comment]
Hi,I cloned the briefcase and downloaded numpy in beeware-venv/lib/python/site-packages, but I didn't find any python libraries containing numpy in xcode projects after I packaged them as xcode projects
