### ISSUE TITLE
Hi,I have a question about using opencv-python in iOS

### ISSUE THREAD

**Issue by GongWeiBinGitHub** [beeware/Python-Apple-support#178]
### What is the problem or limitation you are having?

When generating the xcode project, I imported opencv-python, but the message "ERROR: Failed building wheel for cmake "was displayed
Failed to build cmake
ERROR: Could not build wheels for cmake, which is required to install pyproject.toml-based projects"
I did not find the binary package on anaconda.org. What should I do if I want to import opencv-python into an xcode project

### Describe the solution you'd like

I want to use opencv-python in the generated xcode for iOS project

### Describe alternatives you've considered

I don't have an alternative

**Comment by freakboy3742** [comment]
The answer for this question is the same as the one you raised about numpy. OpenCV is a package that has binary modules. Those modules need to be compiled for iOS.

Unfortunately, we haven't yet build OpenCV for iOS as part of the BeeWare project.

**Comment by GongWeiBinGitHub** [comment]
That said, opencv-python is currently not available in iOS, so are there any alternatives

**Comment by freakboy3742** [comment]
You'll have to make that decision on your own. I can't judge what your requirements are. The list of packages that BeeWare currently supports is [here](https://anaconda.org/beeware/repo)

**Comment by GongWeiBinGitHub** [comment]
I have some image processing needs that require opencv-python, and if there's no way to do it, I'll have to give up integrating python on ios
