### ISSUE TITLE
Creating pkg of the python apple support 3.9 branch

### ISSUE THREAD

**Issue by evaliu2002** [beeware/Python-Apple-support#185]
### Describe the bug

Hello, I wanted to create a pkg of the python macos folders for any mac users to use python without needing to install python separately and add to env variables but when I opened the pkg on a different device, it said the version isn't compatible. The python worked on my original device though. Any guidance would be amazing, thank you!

The device I made the pkg in is the M1 Macbook Pro 16" using Ventura 13.2.1.
The device I ran the pkg is a virtual M1 Macbook Pro using Ventura 13.2.1.

<img width="227" alt="image" src="https://github.com/beeware/Python-Apple-support/assets/69877857/7e9df730-b955-4185-92e3-53f08f8233b4">

### Steps to reproduce

Clone 3.9 branch of Python-Apple-support in Downloads folder
cd into Python-Apple-support
Run `make`
cd back into Downloads folder
Run `pkgbuild --root ./Python-Apple-support --identifier com.example.package --version 0.2.13 --install-location "/Users/device-name" Python-Apple-support.pkg`

### Expected behavior

I expect the installation of the Python-Apple-support folder to succeed and for the folder to appear in the /Users/device-name folder.

### Environment

- Operating System: Ventura 13.2.1 and 
- Python version: 3.9

**Comment by evaliu2002** [comment]
Much appreciated!

**Comment by freakboy3742** [comment]
I'm not entirely clean on what you're trying do here, or why you'd expect this to work. The Apple Support package isn't intended to be "installable" by itself. It isn't a standalone Python installer - if you want one of those, you can get one from python.org. 

If anything, it's an analog of the Windows "embedded" installer - something that isn't inherently useful by itself, but *can* be embedded into other projects.

Closing on the basis that this is "off label" usage, and it's not clear that what is being proposed should be "on label".
