### ISSUE TITLE
Missing distt folder after running make command and make wheel command

### ISSUE THREAD

**Issue by aditya141025** [beeware/Python-Apple-support#188]
### Describe the bug

I want to use Python Apple Support for getting Python interpreter for iOS . In the **YouTube** tutorial **https://www.youtube.com/watch?v=gznPQpZH1Yc&t=131s** it is shown that he finds iOS related folder under **distt** folder and he drags those files in to Xcode project  and Python interpreter works for iOS. 
But when I'm cloning the Python Apple Support and run make iOS command in terminal, then I can not see the **distt** folde

r in this. Appart from **distt** I get everything.  Please refer the  screenshot.

![Screenshot 2023-10-11 at 5 06 10 PM](https://github.com/beeware/Python-Apple-support/assets/141843545/da6ef325-9b47-4ed6-9ee2-88786263339e)

Below is the screenshot shown in the  youtube tutorial, in which we can se the **distt** folder . 
![Screenshot 2023-10-11 at 5 13 04 PM](https://github.com/beeware/Python-Apple-support/assets/141843545/d8914e4d-f020-4e13-b225-7cb7f3ef72e5)

**Comment by freakboy3742** [comment]
Please refer to the [usage guide}(https://github.com/beeware/Python-Apple-support/blob/main/USAGE.md) for details on how to use the Apple Support package in your own project. 

Also note that the only usage that we *officially* support is Briefcase. We try to maintain the usage guide on a best-effort basis for customized usage, but we don't offer any sort of debugging support for custom usage. The most reliable way to see how to use this support package in your own project is to use Briefcase to generate a working project, then copy over/duplicate any of the details into your own project.
