### ISSUE TITLE
How can i add 3rd Site-packages like pandas, matplotlib, sklearn etc???

### ISSUE THREAD

**Issue by abhishekbiswas772** [beeware/Python-Apple-support#189]
### What is the problem or limitation you are having?

How can i add 3rd Site-packages like pandas, matplotlib, sklearn etc???

### Describe the solution you'd like

Please guide us for same. any way to add in site-packges folder in python run time will help this 

### Describe alternatives you've considered

using REST api method but i dont want it

**Comment by abhishekbiswas772** [comment]
ok, actually I want to integrate any 3rd party packages of Python for testing. (targeting the ios platform)

**Comment by freakboy3742** [comment]
The best documentation I can point you at is the [usage guide](https://github.com/beeware/Python-Apple-support/blob/main/USAGE.md). However, I will reinforce what that usage guide says in the opening: the only officially supported configuration of this project is *using Briefcase*. This project *can* be used by itself; however, it's up to you to work out how to do so.

**Comment by abhishekbiswas772** [comment]
okay sir, thank you for guiding.
