### ISSUE TITLE
Python 3.12 change results in Apple App Store rejection

### ISSUE THREAD

**Issue by efroemling** [beeware/Python-Apple-support#221]
### Describe the bug

Since it is relevant here, I wanted to mention this issue that I recently ran into with Python 3.12 related to App Store reviews.

[Here is my full bug report](https://github.com/python/cpython/issues/120522), but basically there was an 'itms-services' string added to a file in Python 3.12 and it seems Apple is auto-rejecting anything found to contain that string (at least that's what happened to me). After removing that string, my update passed inspection.

I'm curious if you or anyone else around here has run into this?
(Feel free to close this issue; it is just intended as a heads-up for the original one)

### Steps to reproduce

1. Submit an app bundling Python 3.12 or later to Apple's App Store
2. Get rejected

### Expected behavior

Not getting rejected

### Environment

In my case this was Python 3.12 bundled into a Mac app submitted to the Mac App Store.

### Logs

```

```

**Comment by rmartin16** [comment]
crosslink:
- https://github.com/beeware/briefcase/issues/1655

**Comment by freakboy3742** [comment]
@efroemling Thanks for the report; I've responded on the CPython ticket (since ideally, we'll be able to fix this upstream). However, worst case, we can address this in *Briefcase* by applying your "items-services"-string removal patch to this Apple support package. I'm going to be doing some work on this project in the near future to back port the official 3.13 changes (and prepare for an official 3.13 release), so I'll include addressing this issue on my todo list.

**Comment by freakboy3742** [comment]
CPython itself now has an App Store compliance patch that can be used to remove the problematic strings. The builds produced by this project (starting with 3.12-4 and 3.13-1) have this patch applied. The problem doesn't affect CPython 3.11 and earlier.

**Comment by light-bo** [comment]
@freakboy3742  I used version 3.13-b2 to submit for review, but I still seem to encounter this problem. Am I using the wrong build package?

**Comment by freakboy3742** [comment]
@light-bo 3.13-b2 definitely has the patch applied; however, looking at the contents of the published support packages, they have inadvertently included some `.orig` file as a result of applying the patches. 

If you're using Briefcase, you can use the [`cleanup_paths`](https://briefcase.readthedocs.io/en/stable/reference/configuration.html#cleanup-paths) option to remove these `.orig` files (or, for that matter, the entire `test` folder).

I'll need to publish an updated support package; I've opened #239 in the meantime to track the issue. Thanks for the report.
