### ISSUE TITLE
Missing _multiprocessing dylib file

### ISSUE THREAD

**Issue by michaeleisel** [beeware/Python-Apple-support#229]
### Describe the bug

For the new release of Python 3.11, Python complains that it can't import _multiprocessing, and indeed it seems like that dylib is missing

### Steps to reproduce

-

### Expected behavior

-

### Environment

-

**Comment by freakboy3742** [comment]
This is deliberate, not a bug. Multiprocessing isn't supported on iOS. This is something that has been [inherited from the official 3.13 patches](https://docs.python.org/3.13/library/intro.html#ios).

**Comment by michaeleisel** [comment]
The issue is that in files like ios-arm64/lib/python3.11/multiprocessing/connection.py , it still tries to do `import _multiprocessing`

**Comment by mhsmith** [comment]
The entire multiprocessing module is unsupported on iOS. It might be possible to support some of the features which don't require subprocesses, but that hasn't been done yet.
