### ISSUE TITLE
Restore iOS 12 as VERSION_MIN-iOS ?

### ISSUE THREAD

**Issue by michaelrockhold** [beeware/Python-Apple-support#238]
### What is the problem or limitation you are having?

I support a number of devices that will never run anything later than iOS12, so I was dismayed when I found that the Python support package for iOS is built (since commit c53d7bd3) for iOS13, which means that apps built for iOS will crash immediately.
```
dyld: Symbol not found: ___chkstk_darwin
  Referenced from: /private/var/containers/Bundle/Application/279E1A74-1CDE-4DC4-AB77-754BA9C78CD8/Hello World.app/Frameworks/Python.framework/Python (which was built for iOS 13.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /private/var/containers/Bundle/Application/279E1A74-1CDE-4DC4-AB77-754BA9C78CD8/Hello World.app/Frameworks/Python.framework/Python

``` 

### Describe the solution you'd like

My preferred resolution would be that the next release of the Python support library were compiled to be compatible with iOS 12.

### Describe alternatives you've considered

I made a half-hearted attempt to build it for myself, but immediately hit a script issue with xattr, and decided not to head down that way for now.

**Comment by freakboy3742** [comment]
Unfortunately, reverting to iOS 12 isn't an option we're going to pursue. iOS 13 is the default minimum that was approved as part of the PEP 730 work; this was largely driven by one of the binary modules in CPython itself (sqlite3).

This is in combination with the fact that we don't have the resources to support operating systems that vendors themselves aren't supporting. iOS 12 reached EOL in early 2023. For that matter, iOS 13 and 14 are also EOL, but at least at present, we can maintain support for those by doing nothing, which isn't the case for iOS 12.

The support package *should* still compile will a minimum set to iOS 12, except for some additional warnings during compilation. If there are changes we can make to support iOS 12, we're happy to entertain patches; but unless someone provides those patches (and they're not excessively invasive) we're unlikely to restore iOS 12 support.
