### ISSUE TITLE
some troubles about third party like numpy running in iOS 

### ISSUE THREAD

**Issue by mrkizy** [beeware/Python-Apple-support#240]
### Describe the bug

I want to use third party like numpy or other third-party python library in iOS, when I tried to import numpy, an error occurred during execution, like the following:
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Python exception: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
Traceback:
  File "/Users/xxxxxx/Library/Developer/CoreSimulator/Devices/0839ADCE-2FDA-4B5E-B71E-29E8D4D95F10/data/Containers/Bundle/Application/BFF8EBF6-3DD3-4DE0-A2DB-05FB48C4E127/xxxx.app/python/lib/python3.12/site-packages/numpy/__init

### Steps to reproduce

The numpy package is placed in the site-packages directory.（like /xxxx.app/python/lib/python3.12/site-packages/numpy)

### Expected behavior

I can run codes properly in expected

### Environment

- Operating System: iOS
- Python version: 3.12
- Software versions: 
  - Briefcase:
  - Toga:
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
Closing on the basis that this isn't an issue with Python-Apple-support.

You haven't provided enough detail on what you have done to be able to reproduce the problem you've having - but the detail you have provided indicates that you're not using Briefcase to package your project.

Python-Apple-support *can* be used without Briefcase; but using Python-Apple-support in a non-Briefcase project requires additional configuration and build steps. These are documented in the [CPython iOS usage guide](https://docs.python.org/3/using/ios.html).
