### ISSUE TITLE
When I modified python27.zip after, how to re-signature it?

### ISSUE THREAD

**Issue by xietao1233** [beeware/Python-Apple-support#31]

**Comment by freakboy3742** [comment]
It's not clear what it is you're trying to do -can you provide more details?

**Comment by xietao1233** [comment]
I want to delete some files from Python.framework/Versions/2.7/Resources/lib/python27.zip on ios platform, when re-packeage modules to python27.zip file that not been load by program.

**Comment by RiemanZeta** [comment]
I would like to know how to do this too. If you simply unzip the file, make the edits, then zip it back up. I always get a system encoding error on iOS.

**Comment by ColdGrub1384** [comment]
You can just unzip the file. Then set PYTHONHOME to the parent directory containing the unzipped library.

**Comment by ColdGrub1384** [comment]
No, sorry, just set PYTHONHOME to the unzipped directory directly. I also set PYTHONPATH to that but I'm not sure it's necessary.

**Comment by freakboy3742** [comment]
Closing as the question appears to be answered.
