### ISSUE TITLE
Is Unity Python support Possible

### ISSUE THREAD

**Issue by sekkit** [beeware/Python-Apple-support#43]
Mono runtime with Python iOS/android/macOS/Windows support, is that possible?

**Comment by freakboy3742** [comment]
I'm guessing it would be *possible*; however, I have no idea what would be involved, and, it's not a priority for me personally.

**Comment by sekkit** [comment]
I tried with Ironpython and it worked with Unity except il2cpp compilation.
Just load some assemblies dlls from Unity engine,  then you can call them in python script.
But native cpython I reckon PythonNet wrapper should be involved.  https://github.com/pythonnet/pythonnet

**Comment by zhangyl08** [comment]
hi, I successfully run pythonnet in Unity with some mods.
and now working with il2cpp, linking with Python static lib .a, to see if it works fine with iOS.

**Comment by LiYangXuU** [comment]
@zhangyl08 I am also looking for the way to run python(numpy) in Unity iOS project, does PythonNet work fine? or it is better using Python-Apple-support?

**Comment by freakboy3742** [comment]
Closing as the original question has been answered.
