### ISSUE TITLE
Error while building for iOS/macOS

### ISSUE THREAD

**Issue by sekkit** [beeware/Python-Apple-support#44]
xcrun libtool -no_warning_for_no_symbols -static -o build/iOS/Support/OpenSSL/libOpenSSL.a build/iOS/libssl.a build/iOS/libcrypto.a

Build target Python

cd build/macOS/Python-3.6.4-macosx.x86_64 && PATH=/Users/sekkit/Work/Python-Apple-support/build/macOS/Python-3.6.4-macosx.x86_64/dist/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/sw/bin:/sw/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin make all install
/bin/sh: Workbooks.app/Contents/SharedSupport/path-bin: No such file or directory
make: *** [build/macOS/Python-3.6.4-macosx.x86_64/dist/lib/libpython3.6m.a] Error 127

**Comment by freakboy3742** [comment]
Closing due to a lack of detail in the report.
