### ISSUE TITLE
bzip.org permanently down?

### ISSUE THREAD

**Issue by dalcacer** [beeware/Python-Apple-support#53]
[bzip.org](bzip.org) and thus the download for the source package, directs to register.com.
Does anyone has any information on that?

**Comment by freakboy3742** [comment]
Well that sucks. Thanks for the heads up. It was working about a month ago, when I last built the official releases of the support packages.

Unfortunately, I don't know what the canonical URL for the source is now... but we're clearly going to need one. 

If the DNS issue doesn't resolve itself shortly, I can put a copy of the most recent sources somewhere that the build script can reach.

**Comment by dalcacer** [comment]
Yes, it still worked several days ago. I wanted to do a clean build to pinpoint an error regarding the numpy build, when suddenly the buildchain stopped working.

However, for my build, I just switched to the first mirror I could find: https://fossies.org/linux/misc/bzip2-1.0.6.tar.gz/ .
Doesn't seem to be a permanent/good solution, though.

**Comment by freakboy3742** [comment]
Based on the comments on [this LWN article](https://lwn.net/Articles/762264/rss), it appears that the project URL will be going back to https://sourceware.org/bzip2/ (which is where it *was* hosted before it moved to it's own domain).

**Comment by freakboy3742** [comment]
@edsanville The immediate workaround is to pick one of the unofficial download sources for bzip2 v1.0.6 that is listed in this message, and modify the Makefile to reference that location. 

I'm hesitant to modify the official Makefile until a new "official" location for bzip2 is established; however, given it's been over a month, and the promised new location at sourceware hasn't materialised, we may need to resort to picking an unofficial source.

**Comment by edsanville** [comment]
OK, that's what I did.  I switched to the fossies link, which works.

It sounds like that canonical bzip2 link wasn't so canonical after all.

**Comment by freakboy3742** [comment]
It *was* canonical; the problem is that bzip2 is effectively abandonware - it hasn't been updated in several years, but the maintainer has evidently decided they're not going to maintain it any longer.

**Comment by samueljohn** [comment]
It seems somebody has put bzip2 up at sourceforge (why would you want to do that?),however, I verified that the sha256 is identical to the one hosted at the suggested mirror.

Also note [that homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bzip2.rb) also lists that two mirrors and Python-Apple-Support should probably also pick one of these two.

I suggest to merge the pull request #65 because the sha265 is fine.

**Comment by freakboy3742** [comment]
The sourceware link appears to be official (and includes a new release). Link has now been updated.
