### ISSUE TITLE
numpy-iOS, python 3.7

### ISSUE THREAD

**Issue by dalcacer** [beeware/Python-Apple-support#54]
Hi,

I'm still investigating, but the target `numpy-{iOS/macOS}` fails on the 3.7 branch at the following point

```
[...]
error: Command "xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -DNDEBUG -g -fwrapv -O3 -Wall -mios-version-min=7.0 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.iphonesimulator.x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/dalcacer/repositories/privat/github_python_apple_support/build/macOS/python/include/python3.7m -Ibuild/src.iphonesimulator.x86_64-3.7/numpy/core/src/private -Ibuild/src.iphonesimulator.x86_64-3.7/numpy/core/src/npymath -Ibuild/src.iphonesimulator.x86_64-3.7/numpy/core/src/private -Ibuild/src.iphonesimulator.x86_64-3.7/numpy/core/src/npymath -Ibuild/src.iphonesimulator.x86_64-3.7/numpy/core/src/private -Ibuild/src.iphonesimulator.x86_64-3.7/numpy/core/src/npymath -c numpy/random/mtrand/mtrand.c -o build/temp.iphonesimulator.x86_64-3.7/numpy/random/mtrand/mtrand.o -MMD -MF build/temp.iphonesimulator.x86_64-3.7/numpy/random/mtrand/mtrand.o.d" failed with exit status 1
make: *** [build/iOS/packages/numpy/build/temp.iphonesimulator.x86_64-3.7/libpymath.a] Error 1
```

**Comment by Siege097** [comment]
Did this get resolved or is 3.6 the latest python framework that can run numpy

**Comment by dalcacer** [comment]
To be honest: I had no further time to investigate.

As far as I can, see there are no further commits which means, that this ticket is still relevant/up-to-date.

**Comment by dalcacer** [comment]
I'm currently working on a [python 3.6 numpy-1.16.3 build](https://github.com/OtoJig/Python-Apple-support/commit/95190e45ab8043bb488b36cd7e2f5708da435c09).
The 1.16.3 build procedure differs from the current solution, due to the fact that @freakboy3742 already provided an upstream patch for better cross compilation 🎉.

There are some further adjustments on the build procedure and within the source to enable bitcode embedment.

As soon as the 3.6/1.16.3 build is stable and tested, we're trying to approach python 3.7 again.
