### ISSUE TITLE
Numpy-iOS has Non-public API

### ISSUE THREAD

**Issue by zsro** [beeware/Python-Apple-support#58]
My project use the python 3.6 with numpy , it's run prefect
but when i submit project to AppStore，the App Store Connect feedback that some API is non-public
in libnumpy.a
non-public API about this :  _ccopy_, _dcopy_, _scopy_, _xerbla_, _zcopy_ 
how can i fix it

**Comment by freakboy3742** [comment]
Thanks for the feedback - I haven't submitted any apps to the app store with numpy enabled, so I haven't seen this before. There's not going to be a whole lot of options other than turning off the use of those APIs - but I haven't got any idea how complex that will be. As a minimal first step, you can try commenting out those calls as part of the codebase and see what breaks...

**Comment by zsro** [comment]
hello freakboy3742 
thank you for you help, i will try to commenting out those calls or find other API to replace.

**Comment by Siege097** [comment]
did this issue get resolved?

**Comment by freakboy3742** [comment]
@Siege097 No - it hasn't been resolved yet.

**Comment by Siege097** [comment]
Any ideas as to whether this is numpy trying to access Apple's private API or just a naming issue i.e. there are functions within numpy that have the same name as Apple's API.  I did a quick check these functions all seem to be related to FORTRAN.  Not sure what this has to do with Apple or why they would have a problem with it

**Comment by saturnman** [comment]
Just name collision, change numpy internal function name may fix this problem.

**Comment by lerela** [comment]
This could be helpful if you run into this issue: https://github.com/numpy/numpy/issues/16157
A Numpy patch can be found here: https://github.com/lerela/numpy/pull/1

**Comment by freakboy3742** [comment]
Closing as we're deprecating the numpy build system provided by this project, in favour of a more comprehensive approach to support binary packages.
