### ISSUE TITLE
Wrong BZip2 URL

### ISSUE THREAD

**Issue by ColdGrub1384** [beeware/Python-Apple-support#67]
I tried to build and I have this error: tar: Unrecognized archive format tar: Error exit delayed from previous errors. I discovered that http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz points to an HTML page, and if I run `cat` with the tar file, it shows me an HTML page.

**Comment by v1xingyue** [comment]
It's still wrong  bzip2 url .

**Comment by dalcacer** [comment]
There is a pull request pending, but not applied, yet.
For now I would suggest to simply change the URL locally as needed.

**Comment by freakboy3742** [comment]
The reason for the PR not being merged is documented on the PR - I'm not comfortable pointing to a random URL, without at least *some* indication that it's an authoritative (or at least *trusted*) source.
