### ISSUE TITLE
Cannot build NumPy

### ISSUE THREAD

**Issue by ColdGrub1384** [beeware/Python-Apple-support#68]
When I cd into `patch/numpy` and I run `make numpy-iOS`, I have this error:

    make: *** No rule to make target `numpy-iOS'.  Stop.

When I run `make numpy`:

    make: *** No rule to make target `numpy'.  Stop.

I moved the file `Makefile.numpy` to `Makefile` and I can run `make`, but it only downloads the NumPy archive and does nothing, because it runs the first target only. But when I run  `make numpy-iOS`, I have the same error again: 

    make: *** No rule to make target `numpy-iOS'.  Stop.

I tried to comment the first target so if I pass no arguments to `make`, it would run the next target, but I have this error:

    make: Nothing to be done for `numpy'.

Maybe I have the wrong make?

    $ type make
    make is hashed (/usr/bin/make)

    $ make --help
    Usage: make [options] [target] ...
    Options:
    [...]

    This program built for i386-apple-darwin11.3.0
    Report bugs to <bug-make@gnu.org>

**Comment by rakeeb123** [comment]
Same error here. Did anyone solve this?

**Comment by freakboy3742** [comment]
Closing as we're deprecating the numpy build system provided by this project, in favour of a more comprehensive approach to support binary packages.
