### ISSUE TITLE
Matplotlib

### ISSUE THREAD

**Issue by dalcacer** [beeware/Python-Apple-support#73]
I've managed to get matplotlib up and running with the help of [@GoldGrub1384](https://github.com/ColdGrub1384) ( [pyto project](https://github.com/ColdGrub1384/Pyto) ).

The steps necessary are discussed at this [ticket](https://github.com/OtoJig/Python-Apple-support/issues/4) and are provided as shell script (iphone simulator/actual device).

I would love to provide a pull-request, but I‘m not to familiar with the canned recipes used for the makefiles. Can someone help out transforming the shell script approach to a proper makefile? 

Kind Regards
Dorian

**Comment by freakboy3742** [comment]
Apologies for letting this ticket go stale. We've made the decision to abandon the approach to building binary dependencies used by the numpy support for this project. Instead, we're going to look into more generic tooling that can be used for any third party dependency. If you want to follow that work, it's currently logged as beeware/briefcase#471.
