### ISSUE TITLE
How to pack all compiled files to Python.framework and OpenSSL.framework

### ISSUE THREAD

**Issue by v1xingyue** [beeware/Python-Apple-support#74]
I simplely clone this code . 
Just Running  "make iOS" . 
All works fine .
But After a long work , Python-3.7-iOS-support.b1.tar.gz generate  to dist directory . 
But Where is  Python.framework and OpenSSL.framework . 
Unpack this tar.gz file , 

```shell
.
└── Python-3.7-iOS-support.b1
    └── Support
        ├── BZip2
        │   └── Headers
        ├── OpenSSL
        │   └── Headers
        │       └── openssl
        ├── Python
        │   ├── Headers
        │   └── Resources
        │       ├── include
        │       │   └── python3.7m
        │       └── lib
        └── XZ
            └── Headers
                └── lzma

16 directories
```
Many documents use framework file , But how can I pack these files.

**Comment by dalcacer** [comment]
There should be a bunch of libraries as a-files. These can then be included to your XCode project, e.g. via this template: https://github.com/beeware/Python-iOS-template .

```
├── build
│   ├── iOS
│   │   ├── Python-3.7.0-iphoneos.arm64
│   │   ├── Python-3.7.0-iphonesimulator.x86_64
│   │   ├── Support
│   │   ├── VERSIONS
│   │   ├── bzip2
│   │   ├── bzip2-1.0.6-iphoneos.arm64
│   │   ├── bzip2-1.0.6-iphonesimulator.x86_64
│   │   ├── kiwi-1.1.0
│   │   ├── libcrypto.a
│   │   ├── libpng-1.6.37
│   │   ├── libpython3.7m.a
│   │   ├── libssl.a
│   │   ├── openssl
│   │   ├── openssl-1.0.2o-iphoneos.arm64
│   │   ├── openssl-1.0.2o-iphonesimulator.x86_64
│   │   ├── packages
│   │   ├── pyconfig-arm64.h
│   │   ├── pyconfig-x86_64.h
│   │   ├── xz
│   │   ├── xz-5.2.4-iphoneos.arm64
│   │   └── xz-5.2.4-iphonesimulator.x86_64
```

**Comment by freakboy3742** [comment]
It turns out the App Store applies additional verification requirements when code is in a .framework file which prevents the app from being accepted. More recent templates and support packages don't package the code as frameworks; they use bare libraries.
