### ISSUE TITLE
Python3.7.4 support

### ISSUE THREAD

**Issue by zhangyl08** [beeware/Python-Apple-support#77]
as the title indicates

**Comment by efroemling** [comment]
+1 for this.
Alternately, is there any info available about how Python.patch is generated or what it takes to update it for different Python releases?

**Comment by freakboy3742** [comment]
@efroemling The patch is updated using the `make update-patch` build target.

I base it off https://github.com/freakboy3742/cpython, which is a fork of the main CPython repository with iOS patches applied. Whenever I get around to making a new release, I merge updates from the upstream CPython branch repository, and regenerate the patch.

**Comment by freakboy3742** [comment]
Python 3.7 support has now been added.
