### ISSUE TITLE
Unrecognized archive format

### ISSUE THREAD

**Issue by lufinkey** [beeware/Python-Apple-support#79]
After running `make`, I get the following error:

```
mkdir -p build/macOS/bzip2-1.0.6-macosx.x86_64
tar zxf downloads/bzip2-1.0.6.tgz --strip-components 1 -C build/macOS/bzip2-1.0.6-macosx.x86_64
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
make: *** [build/macOS/bzip2-1.0.6-macosx.x86_64/Makefile] Error 1
```

**Comment by freakboy3742** [comment]
Thanks for the report; this is a duplicate of #53.

**Comment by lufinkey** [comment]
So does the project just not work right now or is there a fork or branch I should use instead?

**Comment by freakboy3742** [comment]
Well, it works; you just have to have obtain a copy of bzip2 from somewhere. The URL in #53 is at least one source; it's just not clear if that version is *official*. Put that file in the `downloads` directory, and the build will work.

**Comment by freakboy3742** [comment]
I've just checked, and a new official location is available (which was the old location before bzip2.org was used). I've updated the Makefile to reflect this.

**Comment by lufinkey** [comment]
Awesome thank you so much
