### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by ColdGrub1384** [beeware/Python-Apple-support#81]
Will Python 3.8 be available? I'm trying to compile myself but I'm not succeeding. I removed some patches that were failing but after, I get this error:

> creating Modules/Setup.local
> creating Makefile
> bad word _ctypes/libffi_apple/x86/unix64_x86_64.S in _ctypes _ctypes/_ctypes.c     _ctypes/callbacks.c     _ctypes/callproc.c     _ctypes/stgdict.c     _ctypes/cfield.c     _ctypes/libffi_apple/prep_cif.c     _ctypes/libffi_apple/types.c     _ctypes/libffi_apple/raw_api.c     _ctypes/libffi_apple/java_raw_api.c     _ctypes/libffi_apple/closures.c     _ctypes/libffi_apple/x86/ffi64_x86_64.c     _ctypes/libffi_apple/x86/ffiw64_x86_64.c     _ctypes/libffi_apple/x86/unix64_x86_64.S     _ctypes/libffi_apple/x86/win64_x86_64.S     -I$(srcdir)/Modules/_ctypes/libffi_apple/include
> \# Build target Python
cd build/macOS/Python-3.8.0-macosx.x86_64 && PATH=/Users/adrianlabbe/Desktop/Python-Apple-support/build/macOS/Python-3.8.0-macosx.x86_64/dist/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin make all install
make[1]: *** No rule to make target `all'.  Stop.
make: *** [build/macOS/Python-3.8.0-macosx.x86_64/dist/lib/libpython3.8m.a] Error 2

**Comment by ColdGrub1384** [comment]
I just noticed that there is a similar issue. #77 I will try this method

**Comment by freakboy3742** [comment]
Unfortunately, I'm not in a position to provide any promises or guarantees about timelines. BeeWare is, at present, a volunteer project, and as such, is constrained by the time that volunteers are able to donate.

I'd like to be able to make this a full-time project - but finding a way to pay the bills is the problem.

**Comment by ColdGrub1384** [comment]
Ok. No problem. If I find a solution, I'll share it here.

**Comment by freakboy3742** [comment]
Python 3.8 support has now been added.
