### ISSUE TITLE
Build issue in 3.7.6

### ISSUE THREAD

**Issue by efroemling** [beeware/Python-Apple-support#84]
I seem to be running into an issue in the latest commits in the 3.7 branch that updated Python to 3.7.6.

If I do a fresh git clone, check out the 3.7 branch, and then do 'make macOS', the build eventually winds up stuck with:

```
# Unpack target Python
mkdir -p build/macOS/Python-3.7.6-macosx.x86_64
tar zxf downloads/Python-3.7.6.tgz --strip-components 1 -C build/macOS/Python-3.7.6-macosx.x86_64
# Apply target Python patches
cd build/macOS/Python-3.7.6-macosx.x86_64 && patch -p1 < /Users/ericf/Desktop/Python-Apple-support/patch/Python/Python.patch
patching file Doc/c-api/arg.rst
Reversed (or previously applied) patch detected!  Assume -R? [n] 
```

**Comment by freakboy3742** [comment]
Thanks for the report. Looks like I generated the patch on a dirty Github checkout. Updated patch incoming shortly.
