### ISSUE TITLE
unable to build python 3.8 for iOS with XCode 11.4.1

### ISSUE THREAD

**Issue by elelay** [beeware/Python-Apple-support#86]
PyOS_BeforeFork PyOS_AfterFork_Child PyOS_AfterFork_Parent are called from [Modules/_posixsubprocess.c](https://github.com/python/cpython/blob/v3.8.1/Modules/_posixsubprocess.c#L689) without checking if HAVE_FORK is defined.

So they are referenced but not defined, so build fails at link.

**Comment by freakboy3742** [comment]
Thanks for the report. I actually fixed this (see #85), but I neglected to push the update to this repository. I've pushed the update now. Sorry for the inconvenience caused; let me know if you have any further problems.
