### ISSUE TITLE
Error when build Python-Apple-support-3.7 for iOS

### ISSUE THREAD

**Issue by fisherjoe** [beeware/Python-Apple-support#88]
When I buld framework in root directory with command "make iOS"，it always failed as follow: 

cp -f /Users/xxx/Downloads/Python-Apple-support-3.7/patch/Python/Setup.embedded build/iOS/Python-3.7.6-iphonesimulator.x86_64/Modules/Setup.embedded
Configure target Python
cd build/iOS/Python-3.7.6-iphonesimulator.x86_64 && PATH=/Users/xxx/Downloads/Python-Apple-support-3.7/build/macOS/Python-3.7.6-macosx.x86_64/dist/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/bin:/usr/local/bin:/Users/xxx/Downloads:/Users/yingzi/Project/Dev/flutter/bin:/Users/xxx/Library/Android/sdk/platform-tools:/usr/local/Cellar/dartsim/6.9.1_1;/Users/yingzi/Project/Dev/apache-jmeter-5.2.1/bin:/Users/xxx/Software/ruby/bin:/Users/xxx/Library/Python/3.7/bin ./configure CC="xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk -mios-version-min=8.0 -fembed-bitcode" LD="xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk -mios-version-min=8.0 -fembed-bitcode" --host=x86_64-apple-ios --build=x86_64-apple-darwin19.4.0 --prefix=/Users/xxx/Downloads/Python-Apple-support-3.7/build/iOS/Python-3.7.6-iphonesimulator.x86_64/dist --without-doc-strings --enable-ipv6 --without-ensurepip ac_cv_file__dev_ptmx=no ac_cv_file__dev_ptc=no 
/bin/sh: /Users/yingzi/Project/Dev/apache-jmeter-5.2.1/bin:/Users/xxx/Software/ruby/bin:/Users/xxx/Library/Python/3.7/bin: No such file or directory
**make: *** [build/iOS/Python-3.7.6-iphonesimulator.x86_64/Makefile] Error 127**

**Comment by freakboy3742** [comment]
If you're getting Python 3.7.6, then your repository is out of date; A current checkout should have 3.7.7. 

However, based on the log you've provided, it looks like your shell environment is configured badly - your PATH definition contains semicolons, which will cause problems on any UNIX build system.
