### ISSUE TITLE
makefile update-patch， Where can I find PYTHON_REPO_DIR used by update-path?

### ISSUE THREAD

**Issue by JunyiXie** [beeware/Python-Apple-support#94]
Where can I find PYTHON_REPO_DIR used by update-patch? 
```
update-patch:
	# Generate a diff from the clone of the python/cpython Github repository
	# Requireds patchutils (installable via `brew install patchutils`)
	if [ -z "$(PYTHON_REPO_DIR)" ]; then echo "\n\nPYTHON_REPO_DIR must be set to the root of your Python github checkout\n\n"; fi
	cd $(PYTHON_REPO_DIR) && git diff -D v$(PYTHON_VERSION) $(PYTHON_VER) | filterdiff -X $(PROJECT_DIR)/patch/Python/diff-exclude.lst -p 1 --clean > $(PROJECT_DIR)/patch/Python/Python.patch
```

**Comment by JunyiXie** [comment]
How does this project generate patches?

**Comment by freakboy3742** [comment]
`PYTHON_REPO_DIR` is the path to a Github checkout of the https://github.com/python/cpython repository or a fork. It generates a diff between the 3.X branch and the 3.X.Y version tag that has been selected (PYTHON_VERSION). 

The specific patches in this repo have been generated from the https://github.com/freakboy3742/cpython fork.
