### ISSUE TITLE
can not build to appstore

### ISSUE THREAD

**Issue by Wconqueror** [beeware/Python-Apple-support#97]
ITMS-90036: This bundle is invalid - The Info.plist file for /Payload/xxx.app/PythonEnvironment.bundle/Python.framework is missing or could not be read.

ITMS-90207: Invalid Bundle - The bundle at '/Payload/xxx.app/PythonEnvironment.bundle/Python.framework' does not contain a bundle executable

what should i do?

**Comment by freakboy3742** [comment]
If you've got a Python.framework, then you're not using the Python-Apple-support-provided build. It's therefore very difficult for us to provide any advice. BeeWare's packaged don't package as a framework, specifically because of App Store restrictions.
