### ISSUE TITLE
Warnings in xcode 12: "ignoring invalid debug info in" 

### ISSUE THREAD

**Issue by siege098** [beeware/Python-Apple-support#98]
I am getting a bunch of warnings when I archive an ios project for release before submitting to the app store.  I think this  just started with the release of Xcode 12.  They only appear when I build for release and not for debugging.  Here are a list of the warnings. They appear in BZzip, XY, Python frameworks.  I think this should not cause performance issues, bit thought I would check with you for suggestions/recommendations.  

![image](https://user-images.githubusercontent.com/66699334/93652183-040e2500-f9c9-11ea-98e8-e0d0503ed9fd.png)

**Comment by freakboy3742** [comment]
Thanks for the report. I can't say I've seen this before, so it's difficult to recommend a course of action - but it's definitely concerning. I would guess that there's some flag in Xcode 12 that has changed/deprecated one of the command line options we're using when compiling the support package - but I have no idea what that would be. If you find out what it is, please let us know.
