### ISSUE TITLE
Question:   add python module with Embedding library with C code?

### ISSUE THREAD

**Issue by liyanhrxy** [beeware/Python-Apple-support#99]
In your doc  [Adding NumPy to your iOS project](https://github.com/beeware/Python-Apple-support/tree/3.6/patch/numpy) section 5, some code like 
```
extern PyMODINIT_FUNC PyInit_multiarray(void);

extern PyMODINIT_FUNC PyInit_umath(void);

extern PyMODINIT_FUNC PyInit_fftpack_lite(void);

extern PyMODINIT_FUNC PyInit__umath_linalg(void);

extern PyMODINIT_FUNC PyInit_lapack_lite(void);

extern PyMODINIT_FUNC PyInit_mtrand(void);`
```
is there necessary  would we  implements those method by ourself? and how can we complete that ?   In my side , some necessary details  were not clear enough in this doc, would you give me your hand?? thanks a lot!!!

**Comment by freakboy3742** [comment]
Those functions are Python module implementation functions. You don't need to write them - they're part of the numpy implementation.
